# Site Settings
title: Seungwook Kim
baseurl: ""
description: Seungwook Kim — Computer Vision Researcher

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  publications:
    output: true
    permalink: /blog/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "blog-post"

# Build settings
encoding: "utf-8"

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
